apiVersion: v1
kind: Service
metadata:
  name: nodegoat
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
  selector:
    app: nodegoat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodegoat-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodegoat
  template:
    metadata:
      labels:
        app: nodegoat
    spec:
      serviceAccountName: nodegoat-admin
      containers:
        - name: nodegoat
          image: jeremyleivers/nodegoat-app:latest
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production" # Adjust as necessary
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/nodegoat"
          command: ["sh", "-c"]
          args:
            - |
              until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done
